import { createClient } from "@supabase/supabase-js";

export default createClient('https://otlcichkogbhsjwtoyzl.supabase.co', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90bGNpY2hrb2diaHNqd3RveXpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE2Njk3ODc0MTAsImV4cCI6MTk4NTM2MzQxMH0.9xx-A22os79bCCuKJvBrNLQFH1HnYo9dQlTAR8sq0vs')
